### PR TITLE
ThinPtr type

### LINKED ISSUE #5: ThinRef, ThinPtr
When trying to remove double indirection in `rowan`'s `cursor` layer, I've noticed that I miss

```rust
pub struct ThinRef<'a, Head, SliceItem> {}

pub struct ThinPtr<Head, SliceItem> {}
```

Unlike `&ThinData` /  `*const ThinData`, these should be one pointer sized

### PR DESCRIPTION
**Pull request by CAD97**
Closes #5

And makes the macro even more weird....

The trait impls now delegate to the fat impl rather than the ThinData behind the pointer, so that we work more generally with pointers of unknown provenance. I also slipped a PartialEq generalization in there.

r? @matklad

### CODE REVIEW

**Comment by CAD97** [comment]
In #6 I worried about `Deref` impls for `ThinPtr`, but these are properly gated on the fat type implementing deref. To be more correct, these impls should probably go through the fat type's deref impl, but we know all of the deref impls used here to be "simple".

**Comment by matklad** [comment]
Hm, in general `Deref` for `ThinPtr` has to be unsafe.. But the Derefe itself obviously isn't where do we gate usnafety then?

**Comment by CAD97** [comment]
Deref for ThinPtr doesn't exist: it expands to


```rust
impl<Head, SliceItem> Deref for ThinPtr<Head, SliceItem>
        where
            NonNull<ThinData<Head, SliceItem>>: Deref,
```

and the `where` condition doesn't hold.

**Comment by CAD97** [comment]
For lack of a better way of sharing it, here's a picture of ThinPtr's doc page:
image

**Comment by CAD97** [comment]
I should note that this (accidentally?) relies on tweaks to "covering impls" in 1.41 in order to provide the `From` impls (that were previously `Into` impls). This is more correct, and I think it's fine to rely on waiting for 1.41?

I could set up autocfg to gate whether `From` or `Into` are implemented directly, but ugh

**Comment by CAD97** [comment]
Barring further improvements or a request otherwise, I plan to bump version and publish v1.1 shortly after it compiles on stable (1.41).

**Pull request merged**
